default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: localhost
  port: 5432
  timeout: 5000

development:
  <<: *default
  database: todo_develop

test:
  <<: *default
  database: todo_test

production:
  database: production
